#include "llama-mtp-vocab-builtin.h"

#include <cstdlib>
#include <cstring>
#include <stdexcept>

// generated by scripts/gen-mtp-vocab-builtin.py: the bitmaps and the table `k_builtins`
#include "llama-mtp-vocab-builtin-data.inc"

const llama_mtp_vocab_builtin * llama_mtp_vocab_builtins() {
    return k_builtins;
}

static int hex_nibble(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

std::vector<int32_t> llama_mtp_vocab_builtin_ids(const llama_mtp_vocab_builtin & b) {
    std::vector<int32_t> ids;
    ids.reserve((size_t) b.n_sel);

    int64_t byte_idx = 0;
    for (const char * const * chunk = b.hex; *chunk != nullptr; ++chunk) {
        const char * s = *chunk;
        const size_t n = std::strlen(s);
        if (n % 2 != 0) {
            throw std::runtime_error("built-in draft vocabulary: odd-length hex chunk");
        }
        for (size_t i = 0; i < n; i += 2, ++byte_idx) {
            const int hi = hex_nibble(s[i]);
            const int lo = hex_nibble(s[i + 1]);
            if (hi < 0 || lo < 0) {
                throw std::runtime_error("built-in draft vocabulary: bad hex digit");
            }
            const int v = (hi << 4) | lo;
            for (int bit = 0; bit < 8; ++bit) {
                if (v & (1 << bit)) {
                    const int64_t id = byte_idx * 8 + bit;
                    if (id >= b.n_vocab) {
                        throw std::runtime_error("built-in draft vocabulary: bit past the vocabulary");
                    }
                    ids.push_back((int32_t) id);
                }
            }
        }
    }
    if (byte_idx != (b.n_vocab + 7) / 8 || (int64_t) ids.size() != b.n_sel) {
        throw std::runtime_error("built-in draft vocabulary: bitmap size or population does not match its header");
    }
    return ids;
}

const llama_mtp_vocab_builtin * llama_mtp_vocab_builtin_find(uint64_t tok_fp, int64_t n_vocab, const char * arch, int64_t size) {
    const llama_mtp_vocab_builtin * best = nullptr;
    for (const llama_mtp_vocab_builtin * b = k_builtins; b->name != nullptr; ++b) {
        if (b->tok_fp != tok_fp || b->n_vocab != n_vocab || arch == nullptr || std::strcmp(b->arch, arch) != 0) {
            continue;
        }
        if (size > 0) {
            if (b->n_sel == size) {
                return b;
            }
            continue;
        }
        if (b->n_sel == 65536) {
            return b;
        }
        if (best == nullptr || b->n_sel > best->n_sel) {
            best = b;
        }
    }
    return best;
}

bool llama_mtp_vocab_parse_auto(const char * value, int64_t & size) {
    size = 0;
    if (value == nullptr || std::strncmp(value, "auto", 4) != 0) {
        return false;
    }
    if (value[4] == '\0') {
        return true;
    }
    if (value[4] != ':' || value[5] == '\0') {
        return false;
    }
    char * end = nullptr;
    const long long n = std::strtoll(value + 5, &end, 10);
    if (end == nullptr || *end != '\0' || n <= 0) {
        return false;
    }
    size = n;
    return true;
}
